### ISSUE TITLE
Return None when whois Internationalized domain name

### ISSUE THREAD

**Issue by guoard** [DannyCork/python-whois#225]
Thank you for your awesome package *)
## Describe the bug
```python
domain = whois.query('münchen.de')
print(domain.__dict__)

domain = whois.query('ایران.ir')
print(domain.__dict__)
```
error:
```
AttributeError                            Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 domain.__dict__
```

**Comment by maarten-boot** [comment]
yes i see that this is creating a error in the latest release but the latest code already solves this

./test2.py -d 'ایران.ir' -v
## ===== TEST DOMAINS
--------------------------------------------------------------------------------
ایران.ir
['ایران', 'ir']
['xn--mgba3a4f16a', 'ir']
                name	"ایران.ir"
                 tld	"ir"
           registrar	"nic.ir"
  registrant_country	""
       creation_date	"None"
     expiration_date	"None"
        last_updated	"None"
              status	""
            statuses	"['']"
              dnssec	"False"
        name_servers	"[]"

I guess we have to wait for the latest code to be released into a pip package, 
meanwhile you could clone the code and us it directly

**Comment by maarten-boot** [comment]
this should now be fixed in vesion 0.9.17

**Comment by guoard** [comment]
domain `ایران.ir` fixed. but `münchen.de` still does not work.

out put:
```
In [2]: import whois

In [3]: domain = whois.query('ایران.ir')

In [4]: print(domain.__dict__)
{'name': 'ایران.ir', 'tld': 'ir', 'registrar': 'nic.ir', 'registrant_country': '', 'creation_date': None, 'expiration_date': None, 'last_updated': None, 'status': '', 'statuses': [''], 'dnssec': False, 'name_servers': []}

In [5]: domain = whois.query('münchen.de')

In [6]: print(domain.__dict__)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 print(domain.__dict__)

AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by maarten-boot** [comment]
yes i see that internationalized is not yet in 0.9.17 so it will be currently only available when downloading the code

**Comment by DannyCork** [comment]
0.9.18 released
